### ISSUE TITLE
Spring release 🌸 (Clockwork 3.0)

### ISSUE THREAD

**Issue by itsgoingd** [itsgoingd/clockwork#232]
This is a meta issue putting together all planned features for the next major Clockwork release (3.0).

### Clockwork server-side

- [x] add authentication support (https://github.com/itsgoingd/clockwork-chrome/issues/33, implemented https://github.com/itsgoingd/clockwork/pull/252, https://github.com/itsgoingd/clockwork-chrome/pull/55)
- [x] add support for dark theme for Clockwork Web (implemented https://github.com/itsgoingd/clockwork/pull/254)
- [x] add support for custom user tabs (implemented https://github.com/itsgoingd/clockwork/issues/14)
- [x] add support for symfony (via web profiler)
- [x] add support for xdebug (implemented https://github.com/itsgoingd/clockwork/pull/271)
- [x] add support for logging full stack traces instead of the `file:line` (in log, queries, etc) (https://github.com/itsgoingd/clockwork/issues/225, implemented https://github.com/itsgoingd/clockwork/pull/250, https://github.com/itsgoingd/clockwork-chrome/pull/53)
- [x] add support for peak memory usage
- [x] add support for recording subrequests (PR https://github.com/itsgoingd/clockwork/pull/249)
- [x] improve data serialization (https://github.com/itsgoingd/clockwork/issues/219, https://github.com/itsgoingd/clockwork/issues/203) (partially implemented https://github.com/itsgoingd/clockwork/pull/222, implemented https://github.com/itsgoingd/clockwork/pull/270)
- [x] improve handling of queries with binary bindings (https://github.com/itsgoingd/clockwork/issues/203#issuecomment-393507547, implemented https://github.com/itsgoingd/clockwork/commit/28bcfcc2eb713d6f2982cdb00f0e460f32ff3997)
- [x] use Laravel 5 contracts, drop Laravel 4 support (implemented https://github.com/itsgoingd/clockwork/pull/221, https://github.com/itsgoingd/clockwork/pull/220)
- [x] require PHP 5.5, use all the good stuff (implemented https://github.com/itsgoingd/clockwork/pull/222)
- [x] register the middleware in boot instead of register method (https://github.com/itsgoingd/clockwork/issues/202, implemented https://github.com/itsgoingd/clockwork/commit/8f2a36bb6e81212a9a19c9d7af20853a50ecdcff)

### Clockwork app

- [x] rework "request" tab to be more useful in general (partially implemented https://github.com/itsgoingd/clockwork-chrome/pull/57)
- [x] rework "timeline" tab to a "performance" tab including useful performance stats from all tabs (implemented https://github.com/itsgoingd/clockwork-chrome/pull/51)
- [x] add support for xdebug (implemented https://github.com/itsgoingd/clockwork-chrome/pull/63)
- [x] improve the timeline component UX (implemented https://github.com/itsgoingd/clockwork-chrome/pull/60)
- [x] add "preserve log" feature like in the "network" dev tools tab (implemented https://github.com/itsgoingd/clockwork-chrome/pull/39)
- [x] add counters with execution time, number of total, read and write queries to the "database" tab (https://github.com/itsgoingd/clockwork/issues/231, implemented https://github.com/itsgoingd/clockwork-chrome/pull/52)
- [x] add ability to search/filter data in tables (database, log, headers, etc) (https://github.com/itsgoingd/clockwork-chrome/issues/37) (PR https://github.com/itsgoingd/clockwork-chrome/pull/48)
- [x] improve distinction of various log levels in the "log" tab (https://github.com/itsgoingd/clockwork-chrome/issues/38) (PR https://github.com/itsgoingd/clockwork-chrome/pull/49)
- [x] add easily copyable url of the request (https://github.com/itsgoingd/clockwork-chrome/issues/17, implemented https://github.com/itsgoingd/clockwork-chrome/pull/57)
- [x] add support for dark theme when running standalone (implemented https://github.com/itsgoingd/clockwork-chrome/pull/50)
- [x] add support for recording subrequests (PR https://github.com/itsgoingd/clockwork-chrome/pull/46)
- [x] improve the behavior of requests list to be more stable in various edge cases (https://github.com/itsgoingd/clockwork-chrome/issues/40) (partially implemented https://github.com/itsgoingd/clockwork-chrome/pull/41)
- [x] tweak the highlight color in dark theme (https://github.com/itsgoingd/clockwork-chrome/issues/36)
- [x] fix requests list header sizes if scroll-bar is shown (https://github.com/itsgoingd/clockwork-chrome/issues/35)
- [x] unify extensions to use webRequest api for observing HTTP requests

### Under consideration

- add support for an on-demand mode where Clockwork is active only when the extension is open (https://github.com/itsgoingd/clockwork-chrome/issues/7)
- add "response" tab for simple responses (https://github.com/itsgoingd/clockwork/issues/127)
- add support for gzip compression for the file storage
- add request replay support

**Comment by fgilio** [comment]
I'm so pumped for this release :P	
Here are my 2 cents [Disable collecting for Laravel Horizon requests](https://github.com/itsgoingd/clockwork/pull/272)

**Comment by joskfg** [comment]
I see that you finally tagged v3.0, Is the final release?

**Comment by itsgoingd** [comment]
Yeah, 3.0 is finally out, blog post here - https://underground.works/blog/clockwork-3.0-now-available

New issue for tracking progress on the next release - https://github.com/itsgoingd/clockwork/issues/274
