### ISSUE TITLE
Spring release 🌸 (Clockwork 5.1)

### ISSUE THREAD

**Issue by itsgoingd** [itsgoingd/clockwork#497]
This issue tracks the progress on the next minor release (Clockwork 5.1), scheduled for May / June 2021.

Clockwork 5.1 will be a pretty small release, adding minor features and fixes, so we can focus on a big major 6.0 release.

## Must have

The most important changes most likely to make it into the release.

- [x] Laravel Octane support - [pull](https://github.com/itsgoingd/clockwork/pull/501)
- [x] copy GET requests URL including query string - [pull](https://github.com/itsgoingd/clockwork/pull/502)
- [x] web-interface support in the vanilla integration - [feat](https://github.com/itsgoingd/clockwork/issues/486), [pull](https://github.com/itsgoingd/clockwork/pull/503)
- [x] ability to collect cache queries without data - [feat](https://github.com/itsgoingd/clockwork/issues/471), [pull](https://github.com/itsgoingd/clockwork/pull/488)
- [x] ability to collect routes without third-party routes - [feat](https://github.com/itsgoingd/clockwork/issues/493), [pull](https://github.com/itsgoingd/clockwork/pull/504)
    - possibly with more control over which routes are collected
- [ ] support collecting multi-channel notifications - [feat](https://github.com/itsgoingd/clockwork/issues/484)
- [x] update recommended sublime URL handler - [feat](https://github.com/itsgoingd/clockwork/issues/472)
- [x] fix popovers overflowing from the content section - [bug](https://github.com/itsgoingd/clockwork/issues/487)
- [x] fix toolbar details button not using configured web-interface uri
- [x] fix profiler values showing wrong unit in Xdebug 3 - [bug](https://github.com/itsgoingd/clockwork/issues/468)
- [x] improve behavior of disabled "keep requests log" in web version - [feature](https://github.com/itsgoingd/clockwork/issues/489)
- [ ] improve detection of N+1 queries interaction with some query builder options - [bug](https://github.com/itsgoingd/clockwork/issues/414)
- [x] fix "show more" for chained exceptions in the log tab - [bug](https://github.com/underground-works/clockwork-app/issues/71)
- [x] fix "data" sidebar section for various non-standard requests
- [x] fix cookies api not working in Firefox - [bug](https://github.com/underground-works/clockwork-app/issues/82)
- [ ] user-interface refinements

## Nice to have

The less important changes and changes unlikely to make it due to time constraints or implementation concerns.

- [ ] show duplicate queries in the performance tab
- [ ] support collecting of sizes of cache values - [feat](https://github.com/itsgoingd/clockwork/issues/471)
- [ ] add Laravel authentication support
- [ ] improve toolbar to show Ajax requests - [feat](https://github.com/itsgoingd/clockwork/issues/486)
- [ ] collect (simple) response
    - main concern here is the response size
- [x] Microsoft Edge build - [feat](https://github.com/underground-works/clockwork-app/issues/83)

## Release schedule

Clockwork follows a loose yearly release schedule with one major release in late summer / fall and multiple minor releases in-between.

- [Clockwork 5.0](https://github.com/itsgoingd/clockwork/issues/403) - November 2020  - previous release
- Clockwork 5.1 - May/June 2021
- [Clockwork 6.0](https://github.com/itsgoingd/clockwork/issues/498) - Summer/Fall 2021

**Comment by spawnia** [comment]
https://github.com/itsgoingd/clockwork/releases/tag/v5.1.0 🚀

**Comment by itsgoingd** [comment]
Oops, forgot to close this one.

 Clockwork 5.1 was released on **07 Aug 2021**.
